### ISSUE TITLE
bueller exception logged after selecting all service policies

### ISSUE THREAD

**Issue by spyhunter99** [mil-oss/fgsms#59]
16/01/17 08:50:13:013 EST]  INFO fgsms.StatusBueller: 1/3 http://desktop-ni28oib:8888/fgsmsServices/services/PCS status is OK
[16/01/17 08:50:13:013 EST]  INFO fgsms.StatusBueller: 2/3 http://desktop-ni28oib:8888/fgsmsServices/services/SS status is OK
[16/01/17 08:50:13:013 EST]  INFO fgsms.StatusBueller: 3/3 http://desktop-ni28oib:8888/fgsmsServices/services/DAS status is OK
[16/01/17 08:50:13:013 EST]  WARN fgsms.StatusBueller:
org.postgresql.util.PSQLException: ERROR: more than one row returned by a subquery used as an expression
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:363)
        at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at org.miloss.fgsms.bueller.Bueller.CleanUpOldStuff(Bueller.java:109)
        at org.miloss.fgsms.bueller.Bueller.Fire(Bueller.java:579)
        at org.miloss.fgsms.auxsrv.BuellerScheduler.execute(BuellerScheduler.java:44)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:223)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
[16/01/17 08:50:13:013 EST]  INFO fgsms.StatusBueller: Bueller cleanup performed in 1ms

**Comment by spyhunter99** [comment]
edit this may have been after removing all status records
