### ISSUE TITLE
java message process thread pool ramp up algorithm

### ISSUE THREAD

**Issue by spyhunter99** [mil-oss/fgsms#85]
the current implementation is creating and destroying a large volume of threads unnecessarily this needs to be fixed

**Comment by spyhunter99** [comment]
after doing the map, it looks like the message processor can handle about 200 messages/sec/thread, seems fairly consistent against several environments.

**Comment by spyhunter99** [comment]
[29/01/17 09:44:57:057 EST]  WARN handler.HandlerChainInvoker: Handler execution raised a runtime exception.
java.lang.IllegalThreadStateException
        at java.lang.Thread.start(Thread.java:705)
        at org.miloss.fgsms.agentcore.MessageProcessor.run(MessageProcessor.java:604)
        at org.miloss.fgsms.agentcore.MessageProcessor.processMessageOutput(MessageProcessor.java:442)
        at org.miloss.fgsms.agentcore.MessageProcessor.processMessageOutput(MessageProcessor.java:378)
        at org.miloss.fgsms.agents.JAXWSGenericCommonMessageHandler.ProcessResponse(JAXWSGenericCommonMessageHandler.java:496)
        at org.miloss.fgsms.agents.JAXWSGenericAgent.ProcessOutboundMessage(JAXWSGenericAgent.java:101)
        at org.miloss.fgsms.agents.JAXWSGenericAgent.handleMessage(JAXWSGenericAgent.java:63)
        at org.miloss.fgsms.agents.JAXWSGenericAgent.handleMessage(JAXWSGenericAgent.java:40)
        at org.apache.cxf.jaxws.handler.HandlerChainInvoker.invokeHandleMessage(HandlerChainInvoker.java:359)
        at org.apache.cxf.jaxws.handler.HandlerChainInvoker.invokeHandlerChain(HandlerChainInvoker.java:255)
        at org.apache.cxf.jaxws.handler.HandlerChainInvoker.invokeProtocolHandlers(HandlerChainInvoker.java:132)
        at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor.handleMessageInternal(SOAPHandlerInterceptor.java:169)
        at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor.access$000(SOAPHandlerInterceptor.java:71)
        at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor$1.handleMessage(SOAPHandlerInterceptor.java:81)
        at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor$1.handleMessage(SOAPHandlerInterceptor.java:78)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
        at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:81)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:241)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:286)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:206)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:262)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:615)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
[29/01/17 09:44:57:057 EST]  INFO fgsms.Agents: CXF stack detected, adding SSL information
[29/01/17 09:44:57:057 EST]  WARN phase.PhaseInterceptorChain: Interceptor for {urn:org:miloss:fgsms:services:interfaces:dataAccessService}dataAccessService#{urn:org:miloss:fgsms:services:interfaces:dataAccessService}GetRecentMessageLogs has thrown exception, unwinding now
java.lang.IllegalThreadStateException
        at java.lang.Thread.start(Thread.java:705)
        at org.miloss.fgsms.agentcore.MessageProcessor.run(MessageProcessor.java:604)
        at org.miloss.fgsms.agentcore.MessageProcessor.processMessageOutput(MessageProcessor.java:442)
        at org.miloss.fgsms.agentcore.MessageProcessor.processMessageOutput(MessageProcessor.java:378)
        at org.miloss.fgsms.agents.JAXWSGenericCommonMessageHandler.ProcessResponse(JAXWSGenericCommonMessageHandler.java:496)
        at org.miloss.fgsms.agents.JAXWSGenericAgent.ProcessOutboundMessage(JAXWSGenericAgent.java:101)
        at org.miloss.fgsms.agents.JAXWSGenericAgent.handleMessage(JAXWSGenericAgent.java:63)
        at org.miloss.fgsms.agents.JAXWSGenericAgent.handleMessage(JAXWSGenericAgent.java:40)
        at org.apache.cxf.jaxws.handler.HandlerChainInvoker.invokeHandleMessage(HandlerChainInvoker.java:359)
        at org.apache.cxf.jaxws.handler.HandlerChainInvoker.invokeHandlerChain(HandlerChainInvoker.java:255)
        at org.apache.cxf.jaxws.handler.HandlerChainInvoker.invokeProtocolHandlers(HandlerChainInvoker.java:132)
        at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor.handleMessageInternal(SOAPHandlerInterceptor.java:169)
        at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor.access$000(SOAPHandlerInterceptor.java:71)
        at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor$1.handleMessage(SOAPHandlerInterceptor.java:81)
        at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor$1.handleMessage(SOAPHandlerInterceptor.java:78)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
        at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:81)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:241)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:286)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:206)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:262)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:615)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
[29/01/17 09:44:57:057 EST]  INFO fgsms.Agents: CXF stack detected, adding SSL information
[29/01/17 09:44:57:057 EST]  INFO fgsms.Agents: fgsms Data Pusher thread is terminating, no data available to send.
[29/01/17 09:44:57:057 EST]  INFO fgsms.Agents: fgsms Data Pusher thread is terminating, no data available to send.
[29/01/17 09:44:57:057 EST]  INFO fgsms.Agents: fgsms Data Pusher thread is terminating, no data available to send.
[29/01/17 09:44:57:057 EST]  INFO fgsms.Agents: fgsms Data Pusher thread is terminating, no data available to send.
[29/01/17 09:44:57:057 EST]  INFO fgsms.Agents: fgsms Data Pusher thread is terminating, no data available to send.
[29/01/17 09:44:57:057 EST]  INFO fgsms.Agents: fgsms Data Pusher thread is terminating, no data available to send.
[29/01/17 09:44:58:058 EST]  INFO fgsms.Agents: Current VM Memory : total = 474480640 free = 127289936
